### ISSUE TITLE
Playing a saved video causes disconnect

### ISSUE THREAD

**Issue by marvinody** [meew0/Lethe#2]
Saved a video, giving me this json file

``` javascript
{"videos":{"suika":{"vid":"Tc8iu0XFUQc","title":"WE ARE JAPANESE GOBLIN","author":"atomicpuppy2","view_count":"276289"}}}
```

Queuing it up with "yt suika" followed by "yt play" causes

```
A:\chrome\Lethe-master\Lethe-master\lethe.js:161
    boundChannel.sendMessage('An error occurred while getting video information! Please try a different video.');
                 ^

TypeError: boundChannel.sendMessage is not a function
    at handleYTError (A:\chrome\Lethe-master\Lethe-master\lethe.js:161:18)
    at A:\chrome\Lethe-master\Lethe-master\lethe.js:79:16
    at A:\chrome\Lethe-master\Lethe-master\node_modules\ytdl-core\lib\info.js:42:21
    at ClientRequest.<anonymous> (A:\chrome\Lethe-master\Lethe-master\node_modules\ytdl-core\lib\request.js:24:9)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:421:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:311:20)
    at emitOne (events.js:77:13)
```

**Comment by meew0** [comment]
This works for me, more investigation is needed here.

**Comment by meew0** [comment]
Does this error still occur?

**Comment by marvinody** [comment]
Haven't had it in a while

**Comment by meew0** [comment]
I'll close it, reopen it if it happens again.
