### ISSUE TITLE
Random crashes when using `list saved`

### ISSUE THREAD

**Issue by meew0** [meew0/Lethe#38]
`list saved` seems to crash the bot sometimes (roughly a 50/50 chance). I don't have a log yet, will add one at some point.

**Comment by meew0** [comment]
Crash log:
```
[TypeError: Saved.saved.videos[key].prettyPrint is not a function]
TypeError: Saved.saved.videos[key].prettyPrint is not a function
    at Client.<anonymous> (/home/meew/Lethe/lethe.js:281:63)
    at emitOne (events.js:78:13)
    at Client.emit (events.js:170:7)
    at WebSocket.websocket.onmessage (/home/meew/Lethe/node_modules/discord.js/lib/Client/InternalClient.js:59:15)
    at WebSocket.onMessage (/home/meew/Lethe/node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:93:20)
    at WebSocket.emit (events.js:173:7)
    at Receiver.ontext (/home/meew/Lethe/node_modules/ws/lib/WebSocket.js:816:10)
    at /home/meew/Lethe/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/home/meew/Lethe/node_modules/ws/lib/Receiver.js:364:5)
```

**Comment by meew0** [comment]
```
[TypeError: Saved.saved.videos[key].prettyPrint is not a function]
TypeError: Saved.saved.videos[key].prettyPrint is not a function
    at Client.<anonymous> (/home/meew/Lethe/lethe.js:266:63)
    at emitOne (events.js:78:13)
    at Client.emit (events.js:170:7)
    at WebSocket.websocket.onmessage (/home/meew/Lethe/node_modules/discord.js/lib/Client/InternalClient.js:59:15)
    at WebSocket.onMessage (/home/meew/Lethe/node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:93:20)
    at WebSocket.emit (events.js:173:7)
    at Receiver.ontext (/home/meew/Lethe/node_modules/ws/lib/WebSocket.js:816:10)
    at /home/meew/Lethe/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/home/meew/Lethe/node_modules/ws/lib/Receiver.js:364:5)
```
