### ISSUE TITLE
yt command does not work

### ISSUE THREAD

**Issue by Leninsky** [meew0/Lethe#50]
I get the following error whenever I say @botname yt SOD7Ni_3NIc and I configured the data and youtube API in lethe-auth.json

```
[root@cp Lethe]# node lethe.js
The lethe-data.json file doesn't exist! This is not an error.
Lethe#master@6a45cb8
[debug] bypassed direct API login, used cached token
Bot mention: <@145260374088876032>
[debug] ready packet took 5ms to process
[debug] ready with 1 servers, 5 channels and 55 users cached.
[debug] removed temporary voice websocket listeners
{ [Error: spawn help ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn help',
  path: 'help',
  spawnargs:
   [ '-loglevel',
     '0',
     '-i',
     '-',
     '-f',
     's16le',
     '-ar',
     '48000',
     '-af',
     'volume=1',
     '-ac',
     2,
     'pipe:1' ] }
Error: spawn help ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

I am using node v5.5.0 and npm 3.7.2.

**Comment by meew0** [comment]
You don't have ffmpeg installed (or it's installed and not in your PATH), install it and put it in your PATH and it should work.

**Comment by Leninsky** [comment]
Good, now I get the following error: (the bot works but I can't hear anything playing)

```
Lethe#master@6a45cb8
[debug] bypassed direct API login, used cached token
Bot mention: <@145260374088876032>
[debug] ready packet took 10ms to process
[debug] ready with 1 servers, 6 channels and 67 users cached.
[debug] removed temporary voice websocket listeners
Got an ECONNRESET! This is *probably* not an error. Stacktrace:
Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at Pipe.onread (net.js:544:26)
```

**Comment by meew0** [comment]
As the error message says, this is not an error, it's to be expected when you use certain commands (most notably `next`). Do you have node-opus installed?
